name: ChangHyeon Nam's Blog
url: 'https://changhyeonnam.github.io'
description: 'notes and thoughts'

exclude: [Gemfile, Gemfile.lock, README.md]

author: 'ChangHyeon Nam'
disqus_shortname: Nam
# google_analytics: G-NN7JP65RMS

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap


sass:
    sass_dir: _sass
    style: :compressed
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-toc
